// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: application_protos/role.proto

/* eslint-disable */

export const protobufPackage = "user";

/** Message for the Role entity */
export interface Role {
  roleId: number;
  roleName: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  parentRoleId: number;
  description: string;
}
