// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: application_protos/user.proto

/* eslint-disable */

export const protobufPackage = "user";

export interface User {
  id: number;
  username: string;
  email: string;
  hashedPassword: string;
  is2faEnabled: boolean;
  twoFactorSecret: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

/** Message for user registration request */
export interface RegisterUserRequest {
  username: string;
  email: string;
  password: string;
}

/** Message for user registration response */
export interface RegisterUserResponse {
  userId: number;
}

/** Message for user login request */
export interface LoginUserRequest {
  username: string;
  password: string;
}

/** Message for user login response */
export interface LoginUserResponse {
  token: string;
}

/** Message for 2-factor verification request */
export interface Verify2FARequest {
  userId: number;
  /** Verification code */
  code: string;
}

/** Message for 2-factor verification response */
export interface Verify2FAResponse {
  success: boolean;
}

/** Service definition for user authentication */
export interface UserAuthService {
  /** API to register a new user */
  RegisterUser(request: RegisterUserRequest): Promise<RegisterUserResponse>;
  /** API to login an existing user */
  LoginUser(request: LoginUserRequest): Promise<LoginUserResponse>;
  /** API for verifying 2-factor authentication */
  Verify2FA(request: Verify2FARequest): Promise<Verify2FAResponse>;
}
