// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: proto/invalid_schema.proto

/* eslint-disable */

export const protobufPackage = "proto_db_translator";

/** Message with intentional errors for validation testing */
export interface InvalidSqlSchema1 {
  /** Error 1: Missing `db_column` annotation, required for all fields. */
  id: number;
}

export interface InvalidSqlSchema2 {
  /** Error 2: Incorrect foreign key referencing a non-existent table. */
  parentId: number;
}

export interface InvalidSqlSchema3 {
  /** Error 3: Duplicate primary key annotation in the same schema. */
  name: string;
}

export interface InvalidSqlSchema4 {
  /** Error 4: Unsupported default function for SQLite. */
  createdAt: Date | undefined;
}

export interface InvalidSqlSchema5 {
  /** Error 5: Invalid character set (not supported by most databases). */
  invalidCharSetColumn: string;
}
