// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: proto/role_hierarchy.proto

/* eslint-disable */

export const protobufPackage = "proto_db_translator";

export interface RoleHierarchy {
  childRoleId: number;
  parentRoleId: number;
}
