package generated_models

// Code generated by xo. DO NOT EDIT.

// RoleHierarchy represents a row from 'prototestdb123.RoleHierarchy'.
type RoleHierarchy struct {
	ChildRoleID  int `json:"child_role_id"`  // child_role_id
	ParentRoleID int `json:"parent_role_id"` // parent_role_id
}
