// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: db-annotations/database_options.proto

/* eslint-disable */

export const protobufPackage = "db_annotations";

/** Enum for supported database column types */
export enum DbColumnType {
  /** DB_TYPE_UNSPECIFIED - Default value for unspecified type */
  DB_TYPE_UNSPECIFIED = 0,
  /** DB_TYPE_INT - Integer type */
  DB_TYPE_INT = 1,
  /** DB_TYPE_VARCHAR - Variable-length string */
  DB_TYPE_VARCHAR = 2,
  /** DB_TYPE_TEXT - Large text field */
  DB_TYPE_TEXT = 3,
  /** DB_TYPE_BOOLEAN - Boolean */
  DB_TYPE_BOOLEAN = 4,
  /** DB_TYPE_DATETIME - Date and time */
  DB_TYPE_DATETIME = 5,
  /** DB_TYPE_FLOAT - Floating-point number */
  DB_TYPE_FLOAT = 6,
  /** DB_TYPE_DOUBLE - Double-precision floating-point */
  DB_TYPE_DOUBLE = 7,
  /** DB_TYPE_BINARY - Binary data */
  DB_TYPE_BINARY = 8,
  UNRECOGNIZED = -1,
}

/** Enum for supported database constraints */
export enum DbConstraint {
  /** DB_CONSTRAINT_UNSPECIFIED - Default value for no constraint */
  DB_CONSTRAINT_UNSPECIFIED = 0,
  /** DB_CONSTRAINT_NOT_NULL - NOT NULL */
  DB_CONSTRAINT_NOT_NULL = 1,
  /** DB_CONSTRAINT_UNIQUE - UNIQUE */
  DB_CONSTRAINT_UNIQUE = 2,
  /** DB_CONSTRAINT_PRIMARY_KEY - PRIMARY KEY */
  DB_CONSTRAINT_PRIMARY_KEY = 3,
  UNRECOGNIZED = -1,
}

/** Enum for supported default values */
export enum DbDefault {
  /** DB_DEFAULT_UNSPECIFIED - No default */
  DB_DEFAULT_UNSPECIFIED = 0,
  /** DB_DEFAULT_FALSE - DEFAULT FALSE */
  DB_DEFAULT_FALSE = 1,
  /** DB_DEFAULT_TRUE - DEFAULT TRUE */
  DB_DEFAULT_TRUE = 2,
  /** DB_DEFAULT_CURRENT_TIMESTAMP - DEFAULT CURRENT_TIMESTAMP */
  DB_DEFAULT_CURRENT_TIMESTAMP = 3,
  /** DB_DEFAULT_ZERO - DEFAULT 0 (for numeric fields) */
  DB_DEFAULT_ZERO = 4,
  /** DB_DEFAULT_EMPTY_STRING - DEFAULT '' (empty string) */
  DB_DEFAULT_EMPTY_STRING = 5,
  /** DB_DEFAULT_CUSTOM - Custom default value */
  DB_DEFAULT_CUSTOM = 6,
  UNRECOGNIZED = -1,
}

export enum DbUpdateAction {
  /** DB_UPDATE_ACTION_UNSPECIFIED - No update action */
  DB_UPDATE_ACTION_UNSPECIFIED = 0,
  /** DB_UPDATE_ACTION_CURRENT_TIMESTAMP - ON UPDATE CURRENT_TIMESTAMP */
  DB_UPDATE_ACTION_CURRENT_TIMESTAMP = 1,
  UNRECOGNIZED = -1,
}

/** Enum for default value functions */
export enum DbDefaultFunction {
  /** DB_DEFAULT_FUNCTION_UNSPECIFIED - No default function */
  DB_DEFAULT_FUNCTION_UNSPECIFIED = 0,
  /** DB_DEFAULT_FUNCTION_UUID - UUID() */
  DB_DEFAULT_FUNCTION_UUID = 1,
  /** DB_DEFAULT_FUNCTION_NOW - NOW() */
  DB_DEFAULT_FUNCTION_NOW = 2,
  UNRECOGNIZED = -1,
}

/** Enum for index types */
export enum DbIndexType {
  /** DB_INDEX_TYPE_UNSPECIFIED - Default value for no index */
  DB_INDEX_TYPE_UNSPECIFIED = 0,
  /** DB_INDEX_TYPE_SIMPLE - Standard index */
  DB_INDEX_TYPE_SIMPLE = 1,
  /** DB_INDEX_TYPE_COMPOSITE - Composite index across multiple columns */
  DB_INDEX_TYPE_COMPOSITE = 2,
  /** DB_INDEX_TYPE_FULLTEXT - Full-text search index */
  DB_INDEX_TYPE_FULLTEXT = 3,
  /** DB_INDEX_TYPE_SPATIAL - Spatial index */
  DB_INDEX_TYPE_SPATIAL = 4,
  UNRECOGNIZED = -1,
}

export enum DbForeignKeyAction {
  /** DB_FOREIGN_KEY_ACTION_UNSPECIFIED - No action */
  DB_FOREIGN_KEY_ACTION_UNSPECIFIED = 0,
  /** DB_FOREIGN_KEY_ACTION_CASCADE - CASCADE */
  DB_FOREIGN_KEY_ACTION_CASCADE = 1,
  /** DB_FOREIGN_KEY_ACTION_SET_NULL - SET NULL */
  DB_FOREIGN_KEY_ACTION_SET_NULL = 2,
  /** DB_FOREIGN_KEY_ACTION_RESTRICT - RESTRICT */
  DB_FOREIGN_KEY_ACTION_RESTRICT = 3,
  /** DB_FOREIGN_KEY_ACTION_NO_ACTION - NO ACTION */
  DB_FOREIGN_KEY_ACTION_NO_ACTION = 4,
  UNRECOGNIZED = -1,
}
