// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.2
// source: proto/invalid_schema.proto

package user

import (
	_ "github.com/imran31415/protobuf-db/db-annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message with intentional errors for validation testing
type InvalidSqlSchema1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error 1: Missing `db_column` annotation, required for all fields.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *InvalidSqlSchema1) Reset() {
	*x = InvalidSqlSchema1{}
	mi := &file_proto_invalid_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidSqlSchema1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidSqlSchema1) ProtoMessage() {}

func (x *InvalidSqlSchema1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invalid_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidSqlSchema1.ProtoReflect.Descriptor instead.
func (*InvalidSqlSchema1) Descriptor() ([]byte, []int) {
	return file_proto_invalid_schema_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidSqlSchema1) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InvalidSqlSchema2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error 2: Incorrect foreign key referencing a non-existent table.
	ParentId int32 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
}

func (x *InvalidSqlSchema2) Reset() {
	*x = InvalidSqlSchema2{}
	mi := &file_proto_invalid_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidSqlSchema2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidSqlSchema2) ProtoMessage() {}

func (x *InvalidSqlSchema2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invalid_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidSqlSchema2.ProtoReflect.Descriptor instead.
func (*InvalidSqlSchema2) Descriptor() ([]byte, []int) {
	return file_proto_invalid_schema_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidSqlSchema2) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type InvalidSqlSchema3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error 3: Duplicate primary key annotation in the same schema.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InvalidSqlSchema3) Reset() {
	*x = InvalidSqlSchema3{}
	mi := &file_proto_invalid_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidSqlSchema3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidSqlSchema3) ProtoMessage() {}

func (x *InvalidSqlSchema3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invalid_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidSqlSchema3.ProtoReflect.Descriptor instead.
func (*InvalidSqlSchema3) Descriptor() ([]byte, []int) {
	return file_proto_invalid_schema_proto_rawDescGZIP(), []int{2}
}

func (x *InvalidSqlSchema3) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InvalidSqlSchema4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error 4: Unsupported default function for SQLite.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *InvalidSqlSchema4) Reset() {
	*x = InvalidSqlSchema4{}
	mi := &file_proto_invalid_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidSqlSchema4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidSqlSchema4) ProtoMessage() {}

func (x *InvalidSqlSchema4) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invalid_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidSqlSchema4.ProtoReflect.Descriptor instead.
func (*InvalidSqlSchema4) Descriptor() ([]byte, []int) {
	return file_proto_invalid_schema_proto_rawDescGZIP(), []int{3}
}

func (x *InvalidSqlSchema4) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type InvalidSqlSchema5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error 5: Invalid character set (not supported by most databases).
	InvalidCharSetColumn string `protobuf:"bytes,5,opt,name=invalid_char_set_column,json=invalidCharSetColumn,proto3" json:"invalid_char_set_column,omitempty"`
}

func (x *InvalidSqlSchema5) Reset() {
	*x = InvalidSqlSchema5{}
	mi := &file_proto_invalid_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidSqlSchema5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidSqlSchema5) ProtoMessage() {}

func (x *InvalidSqlSchema5) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invalid_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidSqlSchema5.ProtoReflect.Descriptor instead.
func (*InvalidSqlSchema5) Descriptor() ([]byte, []int) {
	return file_proto_invalid_schema_proto_rawDescGZIP(), []int{4}
}

func (x *InvalidSqlSchema5) GetInvalidCharSetColumn() string {
	if x != nil {
		return x.InvalidCharSetColumn
	}
	return ""
}

var File_proto_invalid_schema_proto protoreflect.FileDescriptor

var file_proto_invalid_schema_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x62, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x1a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x64, 0x62, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x71, 0x6c, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x31, 0x12, 0x1d, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x0d, 0x90, 0xb5, 0x18, 0x01, 0xa0, 0xb5, 0x18, 0x01, 0xaa, 0xb5, 0x18, 0x01, 0x01, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x71,
	0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x32, 0x12, 0x51, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x34, 0x8a, 0xb5, 0x18,
	0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0xa0, 0xb5, 0x18, 0x01, 0xaa, 0xb5,
	0x18, 0x01, 0x01, 0xd2, 0xb5, 0x18, 0x10, 0x4e, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0xda, 0xb5, 0x18, 0x02, 0x69, 0x64, 0xe0, 0xb5, 0x18,
	0x01, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x11, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x71, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x33,
	0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x16,
	0x8a, 0xb5, 0x18, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x90, 0xb5, 0x18, 0x01, 0xa0, 0xb5, 0x18, 0x02,
	0xaa, 0xb5, 0x18, 0x02, 0x01, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6b, 0x0a, 0x11,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x71, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x34, 0x12, 0x56, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x42, 0x1b, 0x8a, 0xb5, 0x18, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0xa0, 0xb5, 0x18, 0x05, 0xaa, 0xb5, 0x18, 0x01, 0x01, 0xb0, 0xb6, 0x18, 0x01, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x7e, 0x0a, 0x11, 0x49, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x53, 0x71, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x35, 0x12, 0x69,
	0x0a, 0x17, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x5f, 0x73,
	0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x32, 0x8a, 0xb5, 0x18, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0xa0, 0xb5, 0x18, 0x02, 0xaa, 0xb5, 0x18, 0x01, 0x01, 0xa2, 0xb6, 0x18, 0x13,
	0x75, 0x6e, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x72,
	0x73, 0x65, 0x74, 0x52, 0x14, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x68, 0x61, 0x72,
	0x53, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_invalid_schema_proto_rawDescOnce sync.Once
	file_proto_invalid_schema_proto_rawDescData = file_proto_invalid_schema_proto_rawDesc
)

func file_proto_invalid_schema_proto_rawDescGZIP() []byte {
	file_proto_invalid_schema_proto_rawDescOnce.Do(func() {
		file_proto_invalid_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_invalid_schema_proto_rawDescData)
	})
	return file_proto_invalid_schema_proto_rawDescData
}

var file_proto_invalid_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_invalid_schema_proto_goTypes = []any{
	(*InvalidSqlSchema1)(nil),     // 0: proto_db_translator.InvalidSqlSchema1
	(*InvalidSqlSchema2)(nil),     // 1: proto_db_translator.InvalidSqlSchema2
	(*InvalidSqlSchema3)(nil),     // 2: proto_db_translator.InvalidSqlSchema3
	(*InvalidSqlSchema4)(nil),     // 3: proto_db_translator.InvalidSqlSchema4
	(*InvalidSqlSchema5)(nil),     // 4: proto_db_translator.InvalidSqlSchema5
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_invalid_schema_proto_depIdxs = []int32{
	5, // 0: proto_db_translator.InvalidSqlSchema4.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_invalid_schema_proto_init() }
func file_proto_invalid_schema_proto_init() {
	if File_proto_invalid_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_invalid_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_invalid_schema_proto_goTypes,
		DependencyIndexes: file_proto_invalid_schema_proto_depIdxs,
		MessageInfos:      file_proto_invalid_schema_proto_msgTypes,
	}.Build()
	File_proto_invalid_schema_proto = out.File
	file_proto_invalid_schema_proto_rawDesc = nil
	file_proto_invalid_schema_proto_goTypes = nil
	file_proto_invalid_schema_proto_depIdxs = nil
}
