name: Go Coverage and Codecov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests and Upload Coverage
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Update this to your Go version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests with coverage
      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Set CODECOV_TOKEN in your repository secrets
          files: coverage.out
          flags: unittests
          fail_ci_if_error: true
